version: "3.5"
services:
  zookeeper:
    image: zookeeper:3.4.13
    container_name: zookeeper
    hostname: zookeeper
    volumes:
      - /ssd/data/zookeeper/data:/datalog
      - /ssd/data/zookeeper/log:/data
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      #KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10
      KAFKA_OFFSETS_RETENTION_MINUTES: 20160
      KAFKA_HEAP_OPTS: "-Xmx3g -Xms3g"
      KAFKA_LOG_DIRS: /kafka/log
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
    volumes:
      - /ssd/data/kafka/data:/kafka:rw
      - /ssd/data/kafka/log:/opt/kafka/log:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hosts:/etc/hosts:ro
  kafkahq:
    image: tchiotludo/kafkahq
    container_name: kafkahq
    hostname: kafkahq
    ports:
      - 8080:8080
    depends_on:
      - kafka
    volumes:
      - /ssd/kafkahq/kafkahq.yml:/app/application.yml:ro
      - /etc/hosts:/etc/hosts:ro
