version: "3.5"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.3
    container_name: elastic
    hostname: elastic
    ports:
      - 9200:9200
    environment:
      cluster.name: "docker-cluster"
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      discovery.type: single-node
      discovery.zen.ping.unicast.hosts: "elastic1"
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
volumes:
  esdata:
    driver_opts:
      type: none
      device: /ssd/data/elastic
      o: bind
